[tox]
envlist = lint,py{310,311,312,313,314},py310-lowest

[testenv]
dependency_groups = test
deps =
    lowest: sphinx==8.1.0
commands = pytest {posargs}

[testenv:lint]
deps = pre-commit~=4.5
skip_install = true
commands = pre-commit run --all-files

; Below tasks are for development only (not run in CI)
[testenv:watch-readme]
deps = restview
skip_install = true
commands = restview README.rst
